package com.scaler.models;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;

@Getter
@Setter
@MappedSuperclass //defines db inheritance/
public abstract class BaseModel implements Serializable {
    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)//auto increment id , generated by db not us
    private Long id;
    //AUDIT ATTRIBUTES. necessary to make for all table classes to track the errors if any/
    private Date createdAt;
    private Date updatedAt;
    private String createdBy;
    private String updatedBy;
}